when:
  branch:
    - dev
  event:
    - push
steps:
  restore-cache:
    image: dev-scm.shijicloud.com/kunlun/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./repo
        - ./.pnpm-store
      ttl: 180
    # 少数step会有写法方面的差异，比如volumes
    volumes:
      - /backup/tmp/cache:/cache