when:
  branch:
    - dev
  event:
    - push

steps:
  restore-cache:
    image: kunlun-local.shijicloud.com/drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - "./repo"
        - "./.pnpm-store"
    volumes:
      - /backup/tmp/cache:/cache