when:
  branch:
    - dev
  event:
    - push
  path:
    exclude: [ 'kubernetes-yaml/*' ]
    ignore_message: '[ALL]'

steps:
  restore-cache:
    image: kunlun-local.shijicloud.com/drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - "./repo"
        - "./.pnpm-store"
    volumes:
      - /backup/tmp/cache:/cache

  publish-to-docker-latest:
    image: kunlun-local.shijicloud.com/golang:1.20.4-alpine
    environment:
      DOCKER_IMAGE_REGISTRY: registry-vpc.cn-hangzhou.aliyuncs.com
      DOCKER_IMAGE_GROUP: shiji-kunlun
      DOCKER_USER_NAME: blackchocolator
      GO111MODULE: on
      GOPROXY: https://goproxy.cn,direct
    secrets:
    - source: ali_package_registry_password
      target: docker_user_pass
    commands:
      - go build -o scavenger main.go
    when:
      branch:
        - dev
      event:
        - push

  rebuild-cache:
    image: kunlun-local.shijicloud.com/drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - "./repo"
        - "./.pnpm-store"
    volumes:
      - /backup/tmp/cache:/cache

#services:
#  docker-dind:
#    image: dev-scm-local.shijicloud.com/woodpecker-ci/docker:24-dind
#    privileged: true
#    commands: dockerd --tls=false -H tcp://0.0.0.0:2375